micronaut:
  application:
    name: plainJdbc
datasources:
  default:
    url: ${JDBC_URL:`jdbc:oracle:thin:@localhost:11521:XE`}
    username: ${JDBC_USER:SYSTEM}
    password: ${JDBC_PASSWORD:testing12345}
    driverClassName: ${JDBC_DRIVER:oracle.jdbc.driver.OracleDriver}
    schema-generate: NONE
    dialect: ORACLE
    max-pool-size: 10
    max-idle-time: 5
